# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTextEdit, QToolBar, QToolButton, QWidget)
import opt_resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 776)
        icon = QIcon()
        icon.addFile(u":/images/assist_icon.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon1 = QIcon()
        icon1.addFile(u":/images/icons8-quit-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        icon2 = QIcon()
        icon2.addFile(u":/images/icons8-reset-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRefresh.setIcon(icon2)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon3 = QIcon()
        icon3.addFile(u":/images/icons8-copy-paste-64.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon3)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon4 = QIcon()
        icon4.addFile(u":/images/icons8-cut-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon4)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon5 = QIcon()
        icon5.addFile(u":/images/icons8-paste-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon5)
        self.actionHow_to_Use = QAction(MainWindow)
        self.actionHow_to_Use.setObjectName(u"actionHow_to_Use")
        icon6 = QIcon()
        icon6.addFile(u":/images/icons8-help-48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionHow_to_Use.setIcon(icon6)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon7 = QIcon()
        icon7.addFile(u":/images/icons8-about-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon8 = QIcon()
        icon8.addFile(u":/images/icons8-undo-64.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon8)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon9 = QIcon()
        icon9.addFile(u":/images/icons8-redo-64.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon9)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btnLearnMore = QToolButton(self.centralwidget)
        self.btnLearnMore.setObjectName(u"btnLearnMore")
        self.btnLearnMore.setGeometry(QRect(100, 160, 101, 41))
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.btnLearnMore.setFont(font)
        self.txtInputAddresses = QTextEdit(self.centralwidget)
        self.txtInputAddresses.setObjectName(u"txtInputAddresses")
        self.txtInputAddresses.setGeometry(QRect(330, 90, 291, 191))
        font1 = QFont()
        font1.setFamilies([u"Noto Serif"])
        font1.setPointSize(9)
        self.txtInputAddresses.setFont(font1)
        self.txtOptimizedAddresses = QTextEdit(self.centralwidget)
        self.txtOptimizedAddresses.setObjectName(u"txtOptimizedAddresses")
        self.txtOptimizedAddresses.setGeometry(QRect(330, 380, 291, 191))
        self.txtOptimizedAddresses.setFont(font1)
        self.btnOptimize = QPushButton(self.centralwidget)
        self.btnOptimize.setObjectName(u"btnOptimize")
        self.btnOptimize.setGeometry(QRect(70, 380, 171, 51))
        font2 = QFont()
        font2.setPointSize(11)
        self.btnOptimize.setFont(font2)
        self.btnOpenMaps = QPushButton(self.centralwidget)
        self.btnOpenMaps.setObjectName(u"btnOpenMaps")
        self.btnOpenMaps.setGeometry(QRect(70, 520, 171, 51))
        self.btnOpenMaps.setFont(font2)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(330, 50, 281, 31))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Variable Display"])
        font3.setPointSize(12)
        self.label.setFont(font3)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(90, 110, 141, 41))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Variable Display Semil"])
        font4.setPointSize(18)
        font4.setBold(False)
        self.label_4.setFont(font4)
        self.btnCopyLink = QPushButton(self.centralwidget)
        self.btnCopyLink.setObjectName(u"btnCopyLink")
        self.btnCopyLink.setGeometry(QRect(70, 450, 171, 51))
        self.btnCopyLink.setFont(font2)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 340, 301, 31))
        self.label_2.setFont(font3)
        self.lblLogo = QLabel(self.centralwidget)
        self.lblLogo.setObjectName(u"lblLogo")
        self.lblLogo.setGeometry(QRect(440, 620, 181, 61))
        self.lblLogo.setAutoFillBackground(False)
        self.lblLogo.setPixmap(QPixmap(u":/images/Assist-Logo.png"))
        self.lblLogo.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionHow_to_Use)
        self.menuHelp.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionHow_to_Use)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(tooltip)
        self.actionCopy.setToolTip(QCoreApplication.translate("MainWindow", u"Copy highlighted text from the input addresses box", None))
#endif // QT_CONFIG(tooltip)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(tooltip)
        self.actionCut.setToolTip(QCoreApplication.translate("MainWindow", u"Cut highlighted text from the input addresses box", None))
#endif // QT_CONFIG(tooltip)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(tooltip)
        self.actionPaste.setToolTip(QCoreApplication.translate("MainWindow", u"Paste into the input addresses box", None))
#endif // QT_CONFIG(tooltip)
        self.actionHow_to_Use.setText(QCoreApplication.translate("MainWindow", u"How to Use", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About Assist Routing", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo changes in the input addresses box", None))
#endif // QT_CONFIG(tooltip)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"Redo changes in the input addresses box", None))
#endif // QT_CONFIG(tooltip)
        self.btnLearnMore.setText(QCoreApplication.translate("MainWindow", u"Learn More...", None))
        self.btnOptimize.setText(QCoreApplication.translate("MainWindow", u"Optimize", None))
        self.btnOpenMaps.setText(QCoreApplication.translate("MainWindow", u"Open in Maps", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Addresses. Origin address first.", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>How to Use?</p></body></html>", None))
        self.btnCopyLink.setText(QCoreApplication.translate("MainWindow", u"Copy Maps Link", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Optimized results. Approximated.", None))
        self.lblLogo.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

